name: Q2 Workflow

on:
  push:
    paths:
      - README.md
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  create_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get current date and time
      id: datetime
      run: |
        echo "datetime=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Create Q2_archive_README.md
      run: |
        if [ ! -f README.md ]; then
          echo "README.md not found, aborting."
          exit 1
        fi
        echo "Nom: Pois--Bons" > Q2_archive_README.md
        echo "Prénom: Alexandre" >> Q2_archive_README.md
        echo "Date et Heure: ${{ env.datetime }}" >> Q2_archive_README.md
        echo "" >> Q2_archive_README.md
        echo "Contenu de README.md :" >> Q2_archive_README.md
        cat README.md >> Q2_archive_README.md

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git pull --rebase origin main  # Intègre les modifications distantes
        git add Q2_archive_README.md
        git commit -m "Add Q2_archive_README.md with workflow details"
        git push origin main
