name: Q4 Workflow

on:
  push:
    paths:
      - Q4.java
  workflow_dispatch: # Permet d'exécuter le workflow manuellement

jobs:
  create_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Q4_archive_date.txt
      run: |
        # Obtenez la date actuelle au format JJ-MM-AAAA
        current_date=$(date '+%d-%m-%Y')
        
        # Vérifiez que la variable current_date est bien définie
        echo "La date actuelle est : ${current_date}"
        
        # Créez le fichier d'archive avec le nom comprenant la date
        echo "Nom: Pois--Bons" > Q4_archive_${current_date}.txt
        echo "Prénom: Alexandre" >> Q4_archive_${current_date}.txt
        echo "" >> Q4_archive_${current_date}.txt
        echo "Contenu de Q4.java :" >> Q4_archive_${current_date}.txt
        cat Q4.java >> Q4_archive_${current_date}.txt

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit and push Q4_archive_date.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git pull --rebase origin main  # Récupère les modifications distantes
        git add Q4_archive_${current_date}.txt  # Assurez-vous que c'est bien le bon fichier
        git commit -m "Add Q4_archive_${current_date}.txt with Q4.java content"
        git push origin main
