name: Q5 Workflow

on:
  push:
    paths:
      - Q5.java  # Déclenchement du workflow lors d'un changement dans le fichier Q5.java
  workflow_dispatch:  # Permet d'exécuter le workflow manuellement

jobs:
  create_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get current date
      id: get_date
      run: |
        current_date=$(date '+%d-%m-%Y')  # Format de la date JJ-MM-AAAA
        echo "La date actuelle est : ${current_date}"
        echo "current_date=${current_date}" >> $GITHUB_ENV  # Sauvegarde la date dans l'environnement

    - name: Create Q5_archive_date.txt
      run: |
        # Utiliser la variable `current_date` dans le nom du fichier
        echo "Nom: Pois--Bons" > Q5_archive_${{ env.current_date }}.txt
        echo "Prénom: Alexandre" >> Q5_archive_${{ env.current_date }}.txt
        echo "" >> Q5_archive_${{ env.current_date }}.txt
        echo "Contenu de Q5.java :" >> Q5_archive_${{ env.current_date }}.txt
        cat Q5.java >> Q5_archive_${{ env.current_date }}.txt

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit and push Q5_archive_date.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git pull --rebase origin main  # Récupère les modifications distantes
        git add Q5_archive_${{ env.current_date }}.txt  # Ajoute le fichier généré avec la date correcte
        git commit -m "Add Q5_archive_${{ env.current_date }}.txt with Q5.java content"
        git push origin main
